// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdlQyo6NOC1N82cwIZVGZWAZF8g8NNhc0',
    appId: '1:844336216561:web:45fef40bac127c53c5ac50',
    messagingSenderId: '844336216561',
    projectId: 'cookbookia',
    authDomain: 'cookbookia.firebaseapp.com',
    storageBucket: 'cookbookia.appspot.com',
    measurementId: 'G-CBWVBMWJKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyshmOimdPklTuzOeWBW31L7j4PrcdtgY',
    appId: '1:844336216561:android:a2e0f5e626224cdcc5ac50',
    messagingSenderId: '844336216561',
    projectId: 'cookbookia',
    storageBucket: 'cookbookia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjbS5OXKsE2BFt_RKJHwZwXJOK3B15nXU',
    appId: '1:844336216561:ios:e949cce3aff8d56dc5ac50',
    messagingSenderId: '844336216561',
    projectId: 'cookbookia',
    storageBucket: 'cookbookia.appspot.com',
    iosBundleId: 'com.mobile.cookbookIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjbS5OXKsE2BFt_RKJHwZwXJOK3B15nXU',
    appId: '1:844336216561:ios:8586e29628f3c7c3c5ac50',
    messagingSenderId: '844336216561',
    projectId: 'cookbookia',
    storageBucket: 'cookbookia.appspot.com',
    iosBundleId: 'com.example.cookbookIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdlQyo6NOC1N82cwIZVGZWAZF8g8NNhc0',
    appId: '1:844336216561:web:73e9a64a2c7ad4afc5ac50',
    messagingSenderId: '844336216561',
    projectId: 'cookbookia',
    authDomain: 'cookbookia.firebaseapp.com',
    storageBucket: 'cookbookia.appspot.com',
    measurementId: 'G-M9WYVMNWNY',
  );
}
